### ISSUE TITLE
warning: address_prefix deprecated

### ISSUE THREAD

**Issue by MilanNXT** [aztfmod/terraform-azurerm-caf-virtual-network#22]
Warning: "address_prefix": [DEPRECATED] Use the `address_prefixes` property instead.
on /home/vsts_azpcontainer/modules/blueprint_networking.virtual_network/terraform-azurerm-caf-virtual-network-2.0.0/subnet/subnet.tf line 1, in resource "azurerm_subnet" "v_subnet":
1: resource "azurerm_subnet" "v_subnet" {

**Comment by arnaudlh** [comment]
duplicates of #18
